### ISSUE TITLE
Build fails with error "Resource not found" after Packer terminates the source server

### ISSUE THREAD

**Issue by MuriloKomirchuk** [hashicorp/packer-plugin-openstack#105]
#### Overview of the Issue

In v1.1.1 build fails just after Packer terminates the source server. The server is terminated but Packer returns the error _"Error getting server to terminate: Resource not found"_.

#### Reproduction Steps

Simply run a build.

### Plugin and Packer version

Packer version: 1.8.6
packer-plugin-openstack: v1.1.1

### Simplified Packer Buildfile

This buildfile uses block storage volume but I have also tested with no volume and got the same result. 

````
packer {
  required_plugins {
    openstack = {
      version = "1.1.1"
      source = "github.com/hashicorp/openstack"
    }
  }
}

source "openstack" "ol8" {
  username                 = "OS_USERNAME"
  password                 = "OS_PASSWORD"
  identity_endpoint        = "OS_AUTH_URL"
  tenant_id                = "OS_TENANT_ID"
  domain_id                = "OS_DOMAIN_ID"
  region                   = "OS_REGION_NAME"
  insecure                 = true
  source_image             = "xxxxxxxxxxxx"
  flavor                   = "xxxxxxxxxxx"
  config_drive             = true
  networks                 = local.networks
  use_blockstorage_volume  = true
  volume_size              = 20
  image_disk_format        = "qcow2"
  image_name               = "test"
  image_visibility         = "shared"
  image_min_disk           = 20
  ssh_username             = "cloud-user"
  instance_name            = local.instance_name
  ssh_read_write_timeout   = "5m"
}

build {
  name = "OL8 Custom Image"
  sources = ["source.openstack.ol8"]

  provisioner "shell" {
    remote_folder = "/home/cloud-user"
    inline = [
      "sudo timedatectl set-timezone UTC",
      "sudo dnf upgrade -y",
      "sudo reboot"
    ]
    expect_disconnect = true
  }

  provisioner "ansible" {
    pause_before       = "60s"
    galaxy_file        = var.galaxy_file
    playbook_file      = var.playbook_file
    use_proxy          = var.use_proxy  
    extra_arguments    = var.extra_arguments
  }
}
````

### Operating system and Environment details

alpine 3.17.2

### Log Fragments and crash.log files

[Log](https://gist.github.com/MuriloKomirchuk/25d42cbd42ef7f7f2b78149e34369432)

**Comment by drew-viles** [comment]
To add to this, I believe it to be related to [this commit](https://github.com/hashicorp/packer-plugin-openstack/commit/b30391d5c354d0ceb0708ce6477916ac350dc360).

I'm going to see if I can submit a fix here.

**Comment by drew-viles** [comment]
Okay, on further investigation it looks more likely that there is a problem with the OpenStack side of things as we're seeing this: https://bugs.launchpad.net/kolla-ansible/+bug/1991516

I'm happy that, from my side, this isn't a bug at all but is instead an issue with OpenStack and how glance/cinder are managing the upload from volume.

**Comment by nywilken** [comment]
Looking at the comments it seems like this might be an upstream issue. Does the fix in  #118 help this situation?

**Comment by drew-viles** [comment]
I shall test it on my end as soon as possible but I actually chatted with John about this a while back, on Slack as we were seeing similar issues so it may well be the fix we're looking for.

**Comment by chufu011011** [comment]
@drew-viles I also encountered the same problem. My OpenStack is kolla-ansible+ceph; using packer to modify the image fails.

[root@kafka OpenStack]# packer build .
openstack.example: output will be in this color.

==> openstack.example: Loading flavor: 2C_2G
    openstack.example: Verified flavor. ID: 497d72a6-e4e1-4e77-9a60-b7e1e55a5ac7
==> openstack.example: Creating temporary RSA SSH key for instance...
==> openstack.example: Not using temporary keypair
    openstack.example: Found Image ID: 4580a489-6bf4-4ef4-8676-a93e51c7513a
==> openstack.example: Creating volume...
==> openstack.example: Waiting for volume packer_681e32ac-bca7-0832-81fe-a6f40fb24133 (volume id: 63d32a83-1f3e-4807-b968-850923534cc8) to become available...
    openstack.example: Volume ID: 63d32a83-1f3e-4807-b968-850923534cc8
==> openstack.example: Launching server...
==> openstack.example: Launching server...
    openstack.example: Server ID: 90746c63-a401-4873-b686-e1135c40afbd
==> openstack.example: Waiting for server to become ready...
==> openstack.example: Creating floating IP using network 7e4509e4-02d0-4974-be91-3fc5df594958 ...
    openstack.example: Created floating IP: 'cd418cc3-6906-4f3b-94e8-70cc0e001edb' (192.168.0.191)
==> openstack.example: Associating floating IP 'cd418cc3-6906-4f3b-94e8-70cc0e001edb' (192.168.0.191) with instance port...
    openstack.example: Added floating IP 'cd418cc3-6906-4f3b-94e8-70cc0e001edb' (192.168.0.191) to instance!
==> openstack.example: Using SSH communicator to connect: 192.168.0.191
==> openstack.example: Waiting for SSH to become available...
==> openstack.example: Connected to SSH!
==> openstack.example: Provisioning with shell script: /tmp/packer-shell3246649481
    openstack.example: Changing password for user root.
    openstack.example: passwd: all authentication tokens updated successfully.
    openstack.example: execute successful
==> openstack.example: Stopping server: 90746c63-a401-4873-b686-e1135c40afbd ...
    openstack.example: Waiting for server to stop: 90746c63-a401-4873-b686-e1135c40afbd ...
==> openstack.example: Terminating the source server: 90746c63-a401-4873-b686-e1135c40afbd ...
==> openstack.example: Creating the image: 9-new
    openstack.example: Image: 60c13f3e-f925-418a-bbea-bd619c6c909c
==> openstack.example: Waiting for image 9-new (image id: 60c13f3e-f925-418a-bbea-bd619c6c909c) to become ready...
==> openstack.example: Error waiting for image: Resource not found
==> openstack.example: Provisioning step had errors: Running the cleanup provisioner, if present...
==> openstack.example: Deleted temporary floating IP 'cd418cc3-6906-4f3b-94e8-70cc0e001edb' (192.168.0.191)
==> openstack.example: Terminating the source server: 90746c63-a401-4873-b686-e1135c40afbd ...
==> openstack.example: Error terminating server, may still be around: Resource not found
==> openstack.example: Deleting volume: 63d32a83-1f3e-4807-b968-850923534cc8 ...
Build 'openstack.example' errored after 6 minutes 28 seconds: Error waiting for image: Resource not found

==> Wait completed after 6 minutes 28 seconds

==> Some builds didn't complete successfully and had errors:
--> openstack.example: Error waiting for image: Resource not found

==> Builds finished but no artifacts were created.
