### ISSUE TITLE
Error: Unknown source type openstack

### ISSUE THREAD

**Issue by anpolychrono** [hashicorp/packer-plugin-openstack#110]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Code below was working with v1.8.5 but not with the latest version v1.9.2

```
source "openstack" "master" {
  flavor                  = var.flavor
  image_name              = var.master_image_name
  source_image            = var.source_image
  ssh_username            = "localadmin"
  temporary_key_pair_type = "ecdsa"
  ssh_private_key_file    = "ssh_keys/id_ecdsa"
  networks                = var.networks
  availability_zone       = var.availability_zone
  user_data               = templatefile("userdata/master.sh", {public_key=var.public_key})
}

source "openstack" "worker" {
  flavor                  = var.flavor
  image_name              = var.worker_image_name
  source_image            = var.source_image
  ssh_username            = "localadmin"
  temporary_key_pair_type = "ecdsa"
  ssh_private_key_file    = "ssh_keys/id_ecdsa"
  networks                = var.networks
  availability_zone       = var.availability_zone
  user_data               = templatefile("userdata/worker.sh", {public_key=var.public_key})
}

build {
  sources = ["source.openstack.master", "source.openstack.worker"]
  provisioner "shell" {
    inline = [
      "cloud-init status --wait",
    ]
  }
}
```

I am getting the below error: 

```
$ packer validate -var-file=./inputs.pkrvars.hcl .
Error: Unknown source type openstack
  on master-worker.pkr.hcl line 25:
  (source code not available)
known builders: [file azure-dtl null vmware-vmx qemu azure-arm vsphere-iso
amazon-ebsvolume vmware-iso virtualbox-ovf vagrant virtualbox-vm
amazon-ebssurrogate googlecompute virtualbox-iso azure-chroot amazon-instance
vsphere-clone amazon-ebs amazon-chroot docker]
Error: Unknown source type openstack
  on master-worker.pkr.hcl line [25](https://gitlab.patras5g.eu/apolychronopoulos/bake-k8s-node-images-with-packer/-/jobs/23332#L25):
  (source code not available)
known builders: [amazon-ebssurrogate googlecompute amazon-ebsvolume vmware-iso
virtualbox-ovf vagrant virtualbox-vm amazon-chroot docker virtualbox-iso
azure-chroot amazon-instance vsphere-clone amazon-ebs vmware-vmx qemu file
azure-dtl null azure-arm vsphere-iso]

```

#### Reproduction Steps

packer validate -var-file=./inputs.pkrvars.hcl .

### Plugin and Packer version

From `packer version` : v1.9.2

### Simplified Packer Buildfile

Mentioned above

### Operating system and Environment details

Tested on MacOS arm64 and on linux amd64

### Log Fragments and crash.log files
MacBook-Pro:bake-k8s-node-images-with-packer apolychrono$ PACKER_LOG=1 packer validate -var-file=./inputs.pkrvars.hcl .
2023/08/06 12:26:09 [INFO] Packer version: 1.9.2 [go1.20.4 darwin amd64]
2023/08/06 12:26:09 [TRACE] discovering plugins in /usr/local/bin
2023/08/06 12:26:09 [TRACE] discovering plugins in .
2023/08/06 12:26:09 [TRACE] discovering plugins in /Users/apolychrono/.config/packer/plugins
2023/08/06 12:26:09 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2023/08/06 12:26:09 [INFO] PACKER_CONFIG env var set; attempting to open config file: /Users/apolychrono/.packerconfig
2023/08/06 12:26:09 [WARN] Config file doesn't exist: /Users/apolychrono/.packerconfig
2023/08/06 12:26:09 [INFO] Setting cache directory: /Users/apolychrono/.cache/packer
2023/08/06 12:26:09 [TRACE] validateValue: not active for master_image_name, so skipping
2023/08/06 12:26:09 [TRACE] validateValue: not active for networks, so skipping
2023/08/06 12:26:09 [TRACE] validateValue: not active for availability_zone, so skipping
2023/08/06 12:26:09 [TRACE] validateValue: not active for public_key, so skipping
2023/08/06 12:26:09 [TRACE] validateValue: not active for flavor, so skipping
2023/08/06 12:26:09 [TRACE] validateValue: not active for source_image, so skipping
2023/08/06 12:26:09 [TRACE] validateValue: not active for worker_image_name, so skipping

  on master-worker.pkr.hcl line 25:
  (source code not available)

known builders: [googlecompute amazon-ebs docker null vsphere-iso
amazon-instance vsphere-clone amazon-ebssurrogate virtualbox-ovf file azure-arm
virtualbox-iso vagrant amazon-chroot virtualbox-vm vmware-vmx amazon-ebsvolume
qemu vmware-iso azure-dtl azure-chroot]

Error: Unknown source type openstack

  on master-worker.pkr.hcl line 25:
  (source code not available)

known builders: [googlecompute amazon-ebs docker null vsphere-iso
amazon-instance vsphere-clone amazon-ebssurrogate virtualbox-ovf file azure-arm
virtualbox-iso vagrant amazon-chroot virtualbox-vm vmware-vmx amazon-ebsvolume
qemu vmware-iso azure-dtl azure-chroot]

Error: Unknown source type openstack

2023/08/06 12:26:09 [INFO] (telemetry) Finalizing.
  on master-worker.pkr.hcl line 25:
  (source code not available)

known builders: [googlecompute amazon-ebs docker null vsphere-iso
amazon-instance vsphere-clone amazon-ebssurrogate virtualbox-ovf file azure-arm
virtualbox-iso vagrant amazon-chroot virtualbox-vm vmware-vmx amazon-ebsvolume
qemu vmware-iso azure-dtl azure-chroot]

Error: Unknown source type openstack

  on master-worker.pkr.hcl line 25:
  (source code not available)

known builders: [googlecompute amazon-ebs docker null vsphere-iso
amazon-instance vsphere-clone amazon-ebssurrogate virtualbox-ovf file azure-arm
virtualbox-iso vagrant amazon-chroot virtualbox-vm vmware-vmx amazon-ebsvolume
qemu vmware-iso azure-dtl azure-chroot]

2023/08/06 12:26:10 waiting for all plugin processes to complete...
MacBook-Pro:bake-k8s-node-images-with-packer apolychrono$

**Comment by psipher** [comment]
I got the same error and got fixed by adding 
packer {
  required_plugins {
    openstack = {
      version = ">= 1.1.1"
      source  = "github.com/hashicorp/openstack"
    }
  }
}

**Comment by anpolychrono** [comment]
Correct !
